---
# Elixir CircleCI 2.0 configuration file
version: 2
jobs:
  test:
    docker:
      - image: circleci/elixir:1.10.4

    working_directory: ~/repo
    steps:
      - checkout
      - run: mix local.hex --if-missing --force
      - run: mix deps.get
      - run: mix credo -C ci
      - run: mix test

workflows:
  version: 2
  ci:
    jobs:
      - test
